In [2]:
import pandas as pd 
file_path = r"C:\Users\HP\Downloads\sales_data.csv"
df = pd.read_csv(file_path)

(df.head())

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned
0,1001,05-01-2024,East,Corporate,Technology,Wireless Mouse,4.0,25.5,0,No
1,1002,06-01-2024,West,Consumer,Office Supplies,Mechanical Pencil Set,10.0,8,0.1,No
2,1003,07-01-2024,Central,Home Office,Furniture,Ergonomic Chair,1.0,250,0.05,No
3,1004,08-01-2024,South,Consumer,Technology,Bluetooth Speaker,2.0,45,0,Yes
4,1005,09-01-2024,East,Corporate,Office Supplies,Gel Pens 12-Pack,5.0,12,0,No

In [3]:
sr = pd.Series([1,2.5,3,4,5,'a'])
sr

0      1
1    2.5
2      3
3      4
4      5
5      a
dtype: object

In [4]:
df.head()

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned
0,1001,05-01-2024,East,Corporate,Technology,Wireless Mouse,4.0,25.5,0,No
1,1002,06-01-2024,West,Consumer,Office Supplies,Mechanical Pencil Set,10.0,8,0.1,No
2,1003,07-01-2024,Central,Home Office,Furniture,Ergonomic Chair,1.0,250,0.05,No
3,1004,08-01-2024,South,Consumer,Technology,Bluetooth Speaker,2.0,45,0,Yes
4,1005,09-01-2024,East,Corporate,Office Supplies,Gel Pens 12-Pack,5.0,12,0,No

In [6]:
df.shape

(125, 10)

In [8]:
df = df.drop_duplicates()

In [9]:
df.shape

(122, 10)

In [10]:
df.tail(3)

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned
122,1120,03-05-2024,Central,Home Office,Furniture,Ergonomic Chair,1.0,$250,5%,Yes
123,1121,04-05-2024,South,Corporate,Technology,USB-C Hub,3.0,$35,0%,No
124,1122,05-05-2024,East,Consumer,Office Supplies,Sticky Notes Pack,15.0,$3.2,0%,No

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122 entries, 0 to 124
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       122 non-null    int64
 1   OrderDate     122 non-null    object
 2   Region        121 non-null    object
 3   CustomerType  121 non-null    object
 4   Category      121 non-null    object
 5   Product       121 non-null    object
 6   Quantity      121 non-null    float64
 7   UnitPrice     121 non-null    object
 8   Discount      121 non-null    object
 9   Returned      121 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 10.5+ KB

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df =df.drop_duplicates()

In [16]:
text_columns = ['region' , 'customertype' , 'category', 'product', 'Returned']

for col in text_columns :
df[col] = df[col].astype(str).str.strip().str.title()

IndentationError: expected an indented block after 'for' statement on line 3 (3496307409.py, line 4)