In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('cleaned_sales_data.csv')

In [3]:
df.head()

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned,GrossSales,DiscountAmount,NetSales,UnitCost,COGS,GrossProfit,OperatingExpenses,NetProfit
0,1001,2024-05-01,East,Corporate,Technology,Wireless Mouse,4.0,25.5,0.00,No,102.0,0.0,102.0,15.3,61.2,40.8,15.300,25.500
1,1002,2024-06-01,West,Consumer,Office Supplies,Mechanical Pencil Set,10.0,8.0,0.10,No,80.0,8.0,72.0,4.8,48.0,24.0,10.800,13.200
2,1003,2024-07-01,Central,Home Office,Furniture,Ergonomic Chair,1.0,250.0,0.05,No,250.0,12.5,237.5,150.0,150.0,87.5,35.625,51.875
3,1004,2024-08-01,South,Consumer,Technology,Bluetooth Speaker,2.0,45.0,0.00,Yes,90.0,0.0,90.0,27.0,54.0,36.0,13.500,22.500
4,1005,2024-09-01,East,Corporate,Office Supplies,Gel Pens 12-Pack,5.0,12.0,0.00,No,60.0,0.0,60.0,7.2,36.0,24.0,9.000,15.000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OrderID            107 non-null    int64
 1   OrderDate          107 non-null    object
 2   Region             107 non-null    object
 3   CustomerType       107 non-null    object
 4   Category           107 non-null    object
 5   Product            107 non-null    object
 6   Quantity           107 non-null    float64
 7   UnitPrice          107 non-null    float64
 8   Discount           107 non-null    float64
 9   Returned           107 non-null    object
 10  GrossSales         107 non-null    float64
 11  DiscountAmount     107 non-null    float64
 12  NetSales           107 non-null    float64
 13  UnitCost           107 non-null    float64
 14  COGS               107 non-null    float64
 15  GrossProfit        107 non-null    float64
 16  OperatingExpenses  107 non-null    float64
 17  NetProfit          107 non-null    float64
dtypes: float64(11), int64(1), object(6)
memory usage: 15.2+ KB

In [5]:
df.tail()

,OrderID,OrderDate,Region,CustomerType,Category,Product,Quantity,UnitPrice,Discount,Returned,GrossSales,DiscountAmount,NetSales,UnitCost,COGS,GrossProfit,OperatingExpenses,NetProfit
102,1118,2024-01-05,East,Corporate,Technology,Wireless Mouse,4.0,25.5,0.00,No,102.0,0.0,102.0,15.30,61.20,40.80,15.300,25.500
103,1119,2024-02-05,West,Consumer,Office Supplies,Gel Pens 12-Pack,10.0,12.0,0.10,No,120.0,12.0,108.0,7.20,72.00,36.00,16.200,19.800
104,1120,2024-03-05,Central,Home Office,Furniture,Ergonomic Chair,1.0,250.0,0.05,Yes,250.0,12.5,237.5,150.00,150.00,87.50,35.625,51.875
105,1121,2024-04-05,South,Corporate,Technology,Usb-C Hub,3.0,35.0,0.00,No,105.0,0.0,105.0,21.00,63.00,42.00,15.750,26.250
106,1122,2024-05-05,East,Consumer,Office Supplies,Sticky Notes Pack,2.0,3.2,0.00,No,6.4,0.0,6.4,1.92,3.84,2.56,0.960,1.600

In [6]:
df['OrderDate']= pd.to_datetime(df['OrderDate'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OrderID            107 non-null    int64
 1   OrderDate          107 non-null    datetime64[ns]
 2   Region             107 non-null    object
 3   CustomerType       107 non-null    object
 4   Category           107 non-null    object
 5   Product            107 non-null    object
 6   Quantity           107 non-null    float64
 7   UnitPrice          107 non-null    float64
 8   Discount           107 non-null    float64
 9   Returned           107 non-null    object
 10  GrossSales         107 non-null    float64
 11  DiscountAmount     107 non-null    float64
 12  NetSales           107 non-null    float64
 13  UnitCost           107 non-null    float64
 14  COGS               107 non-null    float64
 15  GrossProfit        107 non-null    float64
 16  OperatingExpenses  107 non-null    float64
 17  NetProfit          107 non-null    float64
dtypes: datetime64[ns](1), float64(11), int64(1), object(5)
memory usage: 15.2+ KB

In [ ]:
category_eda = df.groupby('Category')[['NetSales', 'COGS', 'GrossProfit', 'NetProfit']].sum()
category_eda = category_eda.sort_values(by='NetSales', ascending=False)

NameError: name 'df' is not defined